### ISSUE TITLE
Adherence: Change date field to date format

### ISSUE THREAD

**Issue by smburnett** [EyeSeeTea/EDSApp#32]
In the Adherence module - Can we change the "Record Date" column to be an actual date format, rather than an open text field?

**Comment by ifoche** [comment]
@smburnett we can do it, but this would be a new development. At this moment there's no calendar component defined in the system (they're always represented as a textfield). If we change it, it will be changed in every DE whose representation is set as Date, do we want that? @gtrsmith, @rodmelia. Do you confirm that we go for it?

**Comment by gtrsmith** [comment]
We do want this, yes! Whether this is for E2 or E3 is up to you, Ignacio. Is this something that can be handled quickly and easily? Or would it postpone the release of E2?

**Comment by ifoche** [comment]
It is easy/quick to do it, I would say maybe 2-3 hours to implement it

**Comment by smburnett** [comment]
The date format seems to only show up in one of the spaces in the adherence tab. 

![set date pop-up on only one entry in adherence section](https://cloud.githubusercontent.com/assets/18399454/15761118/8aafba98-28e4-11e6-90a2-3167dadb19f6.png)

**Comment by ifoche** [comment]
@gtrsmith this is a content issue. The reason why that is the only field that appears with date format is because I changed only that to test that it was properly working. In principle by changing the Question Type attribute to DATE for any Data Element that is needed to be represented like that should solve the problem. Should I assign this issue to you now or you prefer me to do that? (I think at this moment you know better than me which Programs are supposed to be changed and which DEs exactly in the server but of course with a some time I can review the DEs and do it)

**Comment by gtrsmith** [comment]
Yes, I can do it. Thanks Ignacio - I am assigning it to myself.

**Comment by gtrsmith** [comment]
Issue is fixed

**Comment by gtrsmith** [comment]
Actually, there is a bug here that is very difficult to describe. When I configure a data element as a date, it causes an error in the rest of the table by pushing the rest of the answer options over. You can actually see this in the screenshot above. For the row where there is a date field, there is only one drop down menu to the far right. For all other rows, there are two drop down menus. I will try to take a video to explain but this one is very difficult to describe.

**Comment by gtrsmith** [comment]
Alright - see video [here](https://drive.google.com/open?id=0BwFVG9gNmqDyTzdXamlSR1l5M0U). It is quite a strange bug. Note that in the video, I only edit three rows. The configuration for the three rows is EXACTLY THE SAME, with the only exception that the first row has the 'record date' column set to short text instead of date, where rows 2 and 3 are set to date. As you can see in the video, row 1 acts correctly where rows 2 and 3 do not - the answer options get pushed one to the right for some reason. And then they change when you scroll up and down the page. 

Odd stuff - not a priority for now though. I am resetting all fields back to short text. Priority for E2 is ticket #52 

I also want to find another way to test this aside from using these data elements. I've reset them to short text and I dont want to test with the 1. Adherence program (it will be in use soon). Maybe we can create a new test table with date fields... not sure.

**Comment by rodmelia** [comment]
@gtrsmith - graham: another case of a new feature that was not part of the specs; as results there were new bugs.
